sonar.projectKey=vavilin-di_task-processor
sonar.organization=vavilin-di

sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=src/
sonar.exclusions=**/migrations/**,.venv/**,src/**/__init__.py

sonar.tests=tests/
sonar.test.inclusions=**/test_*.py

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8