name: CI Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality-check.yml

  testing:
    needs: code-quality
    uses: ./.github/workflows/testing.yml

  sonarcloud:
    needs: testing
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}